sed -i 's/bg-black\/85/bg-[#FDFBF7]\/85/g' src/components/Navbar.tsx
sed -i 's/bg-black\/40/bg-[#FDFBF7]\/40/g' src/components/Navbar.tsx
sed -i 's/bg-black\/95/bg-[#FDFBF7]\/95/g' src/components/Navbar.tsx
sed -i 's/text-white/text-[#003BFF]/g' src/components/Navbar.tsx
sed -i 's/text-neutral-400/text-zinc-500/g' src/components/Navbar.tsx
sed -i 's/border-neutral-800/border-zinc-200/g' src/components/Navbar.tsx
sed -i 's/border-neutral-900/border-zinc-200/g' src/components/Navbar.tsx
sed -i 's/border-white/border-[#003BFF]/g' src/components/Navbar.tsx
sed -i 's/hover:text-white/hover:text-[#003BFF]/g' src/components/Navbar.tsx
sed -i 's/text-emerald-400/text-[#003BFF]/g' src/components/Navbar.tsx
sed -i 's/bg-emerald-400/bg-[#003BFF]/g' src/components/Navbar.tsx
sed -i 's/bg-white/bg-[#003BFF]/g' src/components/Navbar.tsx
sed -i 's/text-black/text-white/g' src/components/Navbar.tsx
sed -i 's/hover:bg-neutral-200/hover:bg-blue-700/g' src/components/Navbar.tsx
sed -i 's/hover:bg-zinc-900/hover:bg-[#003BFF]\/10/g' src/components/Navbar.tsx
sed -i 's/pillTextColor="#ffffff"/pillTextColor="#003BFF"/g' src/components/Navbar.tsx
sed -i 's/pillColor="#18181b"/pillColor="#ffffff"/g' src/components/Navbar.tsx
sed -i 's/hoveredPillTextColor="#000000"/hoveredPillTextColor="#ffffff"/g' src/components/Navbar.tsx

