sed -i 's/bg-black/bg-[#FDFBF7]/g' src/components/Footer.tsx
sed -i 's/border-zinc-800/border-zinc-200/g' src/components/Footer.tsx
sed -i 's/text-white/text-[#003BFF]/g' src/components/Footer.tsx
sed -i 's/bg-zinc-950\/20/bg-white/g' src/components/Footer.tsx
sed -i 's/border-zinc-950/border-zinc-200/g' src/components/Footer.tsx
sed -i 's/text-zinc-400/text-zinc-600/g' src/components/Footer.tsx
sed -i 's/hover:text-white/hover:text-[#003BFF]/g' src/components/Footer.tsx
sed -i 's/bg-white/bg-[#003BFF]/g' src/components/Footer.tsx
sed -i 's/text-black/text-white/g' src/components/Footer.tsx
sed -i 's/hover:bg-zinc-200/hover:bg-blue-700/g' src/components/Footer.tsx
